TRAFFIC_LIGHT = "TRAFFIC_LIGHT"
CROSSWALK = "CROSSWALK"
STOP_SIGN = "STOP_SIGN"
YIELD_SIGN = "YIELD_SIGN"
SPEED_BUMP = "SPEED_BUMP"
DRIVEWAY = "DRIVEWAY"
PARKING_LOT = "PARKING_LOT"
GUARDRAIL = "GUARDRAIL"
TRAFFIC_CONE = "TRAFFIC_CONE"
TRAFFIC_BARRIER = "TRAFFIC_BARRIER"

# Traffic light states
TRAFFIC_LIGHT_UNKNOWN = 0
TRAFFIC_LIGHT_ARROW_RED = 1
TRAFFIC_LIGHT_ARROW_YELLOW = 2
TRAFFIC_LIGHT_ARROW_GREEN = 3
TRAFFIC_LIGHT_RED = 4
TRAFFIC_LIGHT_YELLOW = 5
TRAFFIC_LIGHT_GREEN = 6
TRAFFIC_LIGHT_FLASHING_RED = 7
TRAFFIC_LIGHT_FLASHING_YELLOW = 8
