[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "123Drive"
version = "0.1.0"
description = "Format data from 123d format to PufferDrive"
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
  "numpy",
  "joblib",
  "tqdm",
  "matplotlib",
  "py123d",
]

[project.optional-dependencies]
dev = ["ruff"]
viz = ["fastapi", "uvicorn[standard]", "orjson"]
all = ["ruff", "fastapi", "uvicorn[standard]", "orjson"]

[project.scripts]
convert = "bin_factory.main:main"
py123d-docker = "py123d_docker.cli:main"
viz = "viz.server:main"
viz-batch = "viz.plot.batch:main"
viz-png = "viz.plot.png:main"
viz-video = "viz.plot.video:main"

[tool.setuptools.packages.find]
where = ["src", "."]
include = ["bin_factory", "bin_factory.*", "viz", "viz.*", "py123d_docker", "py123d_docker.*"]

[tool.uv.sources]
py123d = { git = "https://github.com/autonomousvision/py123d.git", branch = "main" }
